name: ArenaPVP
main: me.naithantu.ArenaPVP.ArenaPVP
authors: [naithantu, Stoux2]
version: 0.9.0
description: Customisable arena pvp system.
commands:
  pvp:
    description: Main ArenaPVP command. Type /pvp for more info.