name: ArenaPVP
main: me.naithantu.ArenaPVP.ArenaPVP
author: naithantu
version: 0.6.4
description: Customisable arena pvp system.
commands:
  pvp:
    description: Main arenapvp command. Type /pvp for more info.